import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import useUser from '../hooks/useUser'
import styled from 'styled-components'
import React from 'react'

const IndexHeader = styled.header`
  height: 60px;
  background-color: #0a174a;
`;

const IndexMain = styled.main`
height: 60px;
background-color: red;
`;

const IndexFooter = styled.footer`
height: 60px;
background-color: yellow;
`;

const Home: NextPage = () => {
  const { pepe } = useUser();
  console.log(pepe);
  return (
    <React.Fragment>
      <Head>
        <title>Recruit Platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndexHeader>
      </IndexHeader>
      <IndexMain>
      </IndexMain>
      <IndexFooter>
      </IndexFooter>
    </React.Fragment>
  )
}

export default Home
