import type { NextPage } from 'next'
import Head from 'next/head'
import useUser from '../hooks/useUser'
import styled from 'styled-components'
import React from 'react'
import LogOutSection from '../components/LogOutSection'
import LogInSection from '../components/LogInSection'
import LoaderOverlay from '../components/LoaderOverlay'
import Admin from '../components/Admin'
import Postulant from '../components/Postulant'
import Company from '../components/Company'
import { PostulantProvider } from '../contexts/PostulantContext'

const IndexHeader = styled.header`
  height: 60px;
  background-color: #0a174a;
  color: white;
`

const IndexMain = styled.main`
  height: 600px;
`

const IndexFooter = styled.footer`
  height: 30px;
  background-color: black;
`

const UserState = styled.div`
  position: relative;
  float: right;
  height: 100%;
  line-height: 50px;
`

const Home: NextPage = () => {
  const { user, role, postulantId, loading } = useUser()
  return (
    <>
      <Head>
        <title>Recruit Platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndexHeader>
        {/* <Logo>
          Logo
        </Logo> */}
        <UserState>
          {user ? <LogOutSection /> : <LogInSection />}
        </UserState>
      </IndexHeader>
        <LoaderOverlay loading={loading}>
        <IndexMain>
          {role && role === 'postulant' &&
          <PostulantProvider id={postulantId}>
            <Postulant />
          </PostulantProvider>}
          {role && role === 'admin' && <Admin />}
          {role && role === 'company' && <Company />}
        </IndexMain>
      </LoaderOverlay>
      <IndexFooter></IndexFooter>
    </>
  )
}

export default Home
