import type { NextPage } from 'next'
import Head from 'next/head'
import useUser from '../hooks/useUser'
import styled from 'styled-components'
import React from 'react'
import LogOutSection from '../components/LogOutSection'
import LogInSection from '../components/LogInSection'

const IndexHeader = styled.header`
  height: 60px;
  background-color: #0a174a;
  color: white;
`;

const IndexMain = styled.main`
height: 600px;
`;

const IndexFooter = styled.footer`
height: 30px;
background-color: black;
`;

const Logo = styled.footer`
position: relative;
float: left;
width: 100px;
height: 100%;
background-color: black;
`;

const UserState = styled.div`
position: relative;
float: right;
height: 100%;
`;

const Home: NextPage = () => {
  const { user } = useUser();
  return (
    <React.Fragment>
      <Head>
        <title>Recruit Platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndexHeader>
        <Logo>
          Logo
        </Logo>
        <UserState>
          {user ? <LogOutSection /> : <LogInSection />}
        </UserState>
        </IndexHeader>
      <IndexMain>
        {user? user.role : 'not logged'}
      </IndexMain>
      <IndexFooter>
      </IndexFooter>
    </React.Fragment>
  )
}

export default Home
